[project]
name = "ai-agent-fundamentals"
version = "0.1.0"
description = "Simple pydantic agent"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic-ai-slim[openai]>=0.0.14",
    "python-dotenv>=1.0.0",
    "langfuse>=2.0.0",
    "asyncio>=4.0.0",
]
